import { POKEMON_TYPE } from './types'

interface ColorsProps {
  [POKEMON_TYPE: string]: string
}

export const COLORS: ColorsProps = {
  [POKEMON_TYPE.BUG]: '#A6B91A',
  [POKEMON_TYPE.DARK]: '#705746',
  [POKEMON_TYPE.DRAGON]: '#6F35FC',
  [POKEMON_TYPE.ELECTRIC]: '#F7D02C',
  [POKEMON_TYPE.FAIRY]: '#D685AD',
  [POKEMON_TYPE.FIGHTING]: '#C22E28',
  [POKEMON_TYPE.FIRE]: '#EE8130',
  [POKEMON_TYPE.FLYING]: '#A98FF3',
  [POKEMON_TYPE.GHOST]: '#735797',
  [POKEMON_TYPE.GRASS]: '#7AC74C',
  [POKEMON_TYPE.GROUND]: '#E2BF65',
  [POKEMON_TYPE.ICE]: '#96D9D6',
  [POKEMON_TYPE.NORMAL]: '#A8A77A',
  [POKEMON_TYPE.POISON]: '#A33EA1',
  [POKEMON_TYPE.PSYCHIC]: '#F95587',
  [POKEMON_TYPE.ROCK]: '#B6A136',
  [POKEMON_TYPE.STEEL]: '#B7B7CE',
  [POKEMON_TYPE.WATER]: '#6390F0',
}
